이민욱/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('best/', views.best, name = 'best'),
    path('detail/<int:pk>/', views.detail, name = 'detail'),
    path('best/write/', views.write, name = 'write'),
]

이민욱/main/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    author = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)

이민욱/main/views.py
from django.shortcuts import render,redirect
from .models import Post

# Create your views here.

app_name = 'main'
def best(request):
    postlist = Post.objects.all()
    return render(request, 'best/best.html', {'postlist':postlist})

def detail(request, pk):
    post_detail = Post.objects.get(pk=pk)
    return render(request, 'best/detail.html', {'post':post_detail})

def write(request):
    if request.method == 'POST':
        write = Post.objects.create(
            title = request.POST['title'],
            content = request.POST['content'],
            author = request.POST['author'],
        )
        return redirect('main:best')
    return render(request, 'best/write.html')

이민욱/main/templates/best/best.html
{% extends 'base.html' %}

{% block style %}

{% endblock style %}


{% block content %}
  <h1>best main</h1>
  <a href="{% url 'main:write' %}">글쓰기</a>
  {% for list in postlist %}
    <ul>
      <li>
        <a href="{% url 'main:detail' list.pk %}">
          {{list.title}}
        </a>
      </li>
      <li>{{list.content}}</li>
      <li>{{list.author}}</li>
      <li>{{list.created_at}}</li>
    </ul>
  {% endfor %}
{% endblock content %}

이민욱/main/templates/best/detail.html
{% extends 'base.html' %}

{% block style %}

{% endblock style %}


{% block content %}
  <h1>best detail</h1>
  <p>{{post.title}}</p>
  <p>{{post.content}}</p>
  <p>{{post.author}}</p>
  <p>{{post.created_at}}</p>
  <a href="{% url 'main:best' %}">목록으로 이동</a>
{% endblock content %}

이민욱/main/templates/best/write.html
{% extends 'base.html' %}

{% block style %}

{% endblock style %}


{% block content %}
  <form method="POST">
    {% csrf_token %}
    <input type="text" name='title'>
    <textarea name="content" cols="50" rows="10"></textarea>
    <input type="text" name='author'>
    <input type="submit">
  </form>
{% endblock content %}

이민욱/main/templates/free/main.html
{% extends 'base.html' %}

{% block style %}

{% endblock style %}


{% block content %}

{% endblock content %}

이민욱/main/templates/free/write.html
{% extends 'base.html' %}

{% block style %}

{% endblock style %}


{% block content %}

{% endblock content %}