정소담/diaries/urls.py
from django.urls import path
from . import views

app_name = 'diaries'
urlpatterns = [
    path('', views.diary, name='diary'),
    path('<int:pk>/', views.diarypage, name='diarypage'),
    path('write/', views.write, name='write'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name = 'edit'),
    path('calendar/',views.calendar, name='calendar'),
]

정소담/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('records/', include('records.urls')),
    path('', views.main, name='main'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

정소담/records/urls.py
from django.urls import path
from . import views


app_name = 'records'
urlpatterns = [
    path('', views.record, name='record'),
    path('<int:pk>/', views.diary, name='diary'),
    path('write/', views.write, name='write'),
    path('success/', views.success, name='success'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit', views.edit, name = 'edit'),
    path('<int:pk>/update', views.update, name = 'update'),
]

정소담/diaries/models.py
from django.db import models
import os
from django.conf import settings
# Create your models here.



class Diary(models.Model):
    title = models.CharField(max_length=50)
    record_date = models.DateTimeField(null=True, blank=True)
    imgfile = models.ImageField(null=True, upload_to="", blank=True)
    content = models.TextField()

    #게시글 삭제시 첨부한 파일 삭제
    def delete(self, *args, **kargs):
        if self.imgfile:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.imgfile.path))
        super(Diary, self).delete(*args, **kargs)

정소담/records/models.py
from django.db import models
import os
from django.conf import settings

# Create your models here.

class Record(models.Model):
    title = models.CharField(max_length=50)
    record_date = models.DateTimeField(null=True, blank=True)
    imgfile = models.ImageField(null=True, upload_to="", blank=True)
    content = models.TextField()

    #게시글 삭제시 첨부한 파일 삭제
    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)

        if self.imgfile:
            self.imgfile.delete()

정소담/diaries/forms.py
from django import forms
from .models import Diary

class DiaryForm(forms.ModelForm):
    title = forms.CharField(
        label='Title',
        widget=forms.TextInput(
            attrs={
                'placeholder' : '  제목',
                'style' : 'border: 2px rgb(201, 186, 244) solid; border-radius: 10px;'
            },
        )
    )

    record_date = forms.DateField(
        label='Date.',
    widget=forms.DateInput(
        attrs={
                'type': 'date',
                'style' : 'border: 2px rgb(201, 186, 244) solid; border-radius: 10px;'
        },
    )
)
    content = forms.CharField(
    label='Text',
    widget=forms.Textarea(
        attrs={
                'placeholder' : '  내용',
                'cols': '30', 'rows':'5',
                'style' : 'border: 2px rgb(201, 186, 244) solid; border-radius: 10px;'
        }, 
    )
)

    class Meta:
        model = Diary
        fields = '__all__'

정소담/diaries/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Diary
from .forms import DiaryForm
from django.contrib import messages
from datetime import date

# Create your views here.

# @login_required
# def diary_list_by_year(request, year):
#     diaries = Diary.objects.filter(date__year=year)
#     context = {'diaries': diaries}
#     return render(request, 'diary.html', context)

# @login_required
# def diary_list_by_month(request, year, month):
#     diaries = Diary.objects.filter(date__year=year, date__month=month)
#     context = {'diaries': diaries}
#     return render(request, 'diary.html', context)

# @login_required
# def diary_list_by_day(request, year, month, day):
#     diaries = Diary.objects.filter(date__year=year, date__month=month, date__day=day)
#     context = {'diaries': diaries}
#     return render(request, 'diary.html', context)

def diary(request):
    if request.method == 'POST':
        year = request.POST.get('year', date.today().year)
        month = request.POST.get('month', date.today().month)
        day = request.POST.get('day', date.today().day)
        diaries = Diary.objects.order_by('record_date').filter(record_date__year=year, record_date__month=month, record_date__day=day)
        context = {
            'diaries': diaries,
            'years' : range(2020,2024),
            'months' : range(1,13),
            'days' : range(1,32),
        }
        return render(request, 'diaries/diary.html', context)
    else:
        diaries = Diary.objects.order_by('record_date')
        context = {
            'diaries': diaries,
            'years' : range(2020,2024),
            'months' : range(1,13),
            'days' : range(1,32),
        }
        return render(request, 'diaries/diary.html', context)


def diarypage(request, pk):
    diary = Diary.objects.get(pk=pk)
    context = {
        'diary' : diary,
    }
    return render(request,'diaries/diarypage.html', context)


def write(request):
    if request.method == 'POST':
        form = DiaryForm(request.POST, request.FILES)
        if form.is_valid():
            diary = form.save()
            return redirect('diaries:diarypage', diary.pk)
    else:
        form = DiaryForm()
    context = {
        'form' : form,
    }
    return render(request, 'diaries/write.html', context)


def delete(request, pk):
    diary = Diary.objects.get(pk=pk)
    diary.delete()
    return redirect("diaries:diary")


def edit(request, pk):
    if request.method == 'POST':
        diary = Diary.objects.get(pk=pk)
        form = DiaryForm(request.POST, request.FILES, instance=diary)
        if form.is_valid():
            diary = form.save()
            return redirect('diaries:diarypage', diary.pk)
    else:
        diary = Diary.objects.get(pk=pk)
        form = DiaryForm(instance=diary)
    context = {
        'diary': diary,
        'form' : form,
    }
    return render(request, 'diaries/edit.html', context)

def calendar(request):
    diaries = Diary.objects.order_by('record_date')
    if request.method == 'POST':
        form = DiaryForm(request.POST, request.FILES)
        if form.is_valid():
            diary = form.save()
            return redirect('diaries:diarypage', diary.pk)
    else:
        form = DiaryForm()
    context = {
        'form' : form,
        'diaries': diaries,
    }
    return render(request,'diaries/calendar.html', context)

정소담/records/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from .models import Record

# Create your views here.

def record(request, year=None, month=None):
    records = Record.objects.order_by('record_date')
    year = request.GET.get('year')
    month = request.GET.get('month')

    if year and month:
        records = records.filter(record_date__year=year, record_date__month=month)

    context = {
        'records' : records,
        'years' : range(2020,2024),
        'months' : range(1,13),
    }


    return render(request, 'records/record.html', context)  

def diary(request, pk):
    record = Record.objects.get(pk=pk)
    context = {
        'record' : record,
    }
    return render(request,'records/diary.html', context)

def write(request):
    return render(request, 'records/write.html')

def success(request):
    title = request.POST['title']
    record_date = request.POST['record_date']
    imgfile = request.FILES.get('imgfile')
    content = request.POST['content']

    record = Record(title = title, record_date=record_date, imgfile=imgfile, content = content)
    record.save()
    
    return redirect("records:diary", record.pk)

def delete(request, pk):
    record = Record.objects.get(pk=pk)
    record.delete()

    return redirect("records:record")

def edit(request, pk):
    record = Record.objects.get(pk=pk)
    context = {
        'record' : record,
    }

    return render(request,'records/edit.html',context)

def update(request,pk):
    record = get_object_or_404(Record, pk=pk)

    if request.method == 'POST':
        if request.FILES.get('imgfile'):
            record.imgfile = request.FILES['imgfile']

        record.title = request.POST.get('title')
        record.record_date = request.POST.get('record_date')
        record.content = request.POST.get('content')
        record.save()

        return redirect('records:diary', record.pk)
    else:
        return render(request, 'edit.html', {'record': record})

정소담/records/templates/records/diary.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'records/style.css' %}">
{% endblock style %}

{% block content %}
<div class="container m-5 text-center">
  <h1> {{record.record_date|date:'Y/m/d'}} 의 기록</h1>
  <h3> {{record.title}} </h3>
  {% if record.imgfile %}
  <img src="{{ record.imgfile.url }}" alt="">
  {% endif %}
  <h4>{{record.content}}</h4>

  <a href="{% url 'records:edit' record.pk %}" class = "me-2">수정</a>
  <a href="{% url 'records:delete' record.pk %}" class = "me-2" onclick="return confirm('정말 삭제하시겠습니까?')">삭제</a>
  <a href="{% url 'records:record' %}">뒤로가기</a>
</div>
{% endblock content %}

정소담/records/templates/records/edit.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'records/style.css' %}">
{% endblock style %}


{% block content %}

<h1>Today record</h1>

<form action="{% url 'records:update' record.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <label for="title">Title</label>
        <input type="text" class="form-control" name="title" id="title" value="{{ record.title }}">
    </div>
    <div>
        <label for="record_date">Date</label>
        <input type="date" class="form-control" name="record_date" id="record_date"  value="{{ record.record_date|date:'Y-m-d' }}">
    </div>
    <div class="form-group">
        <label for="imgfile">Image:</label>
        {% if record.imgfile %}
        <img src="{{ record.imgfile.url }}" width="200">
        {% endif %}
        <input type="file" class="form-control-file" id="imgfile" name="imgfile">
    </div>
    <div>
        <label for="content">Content</label>
        <textarea name="content" class="form-control" id="content" cols="30" rows="5">{{ record.content }}</textarea>
    </div>
    <div style="display: flex;justify-content: center;align-items: center;">
        <input class="btn" style="color:pink; font-size:30px;" type="submit" id='submit-button' value="Save">
        <a href="{% url 'records:diary' record.pk %}" style="font-size:30px;">Back</a>
    </div>
</form>

{% endblock content %}

정소담/records/templates/records/record.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'records/style.css' %}">
{% endblock style %}

{% block content %}


<div class="container">
    <div class="dairy_header">
    <h1>Diary</h1>
    <a style="color:pink; font-size:20px; margin-left:10px;" href="{% url 'records:write' %}">+일기쓰기</a></h1>
    </div>
    <form action="{% url 'records:record' %}" method="get" class="text-center">
        <label for="year">Year:</label>
        <select name="year" id="year">
            <option value="">Select year</option>
            {% for year in years %}
              {% if year == selected_year %}
                <option value="{{ year }}" selected>{{ year }}년</option>
              {% else %}
                <option value="{{ year }}">{{ year }}년</option>
              {% endif %}
            {% endfor %}
        </select>
        <label for="month">Month:</label>
        <select name="month" id="month">
            <option value="">Select month</option>
            {% for month in months %}
                <option value="{{ month }}"> {{ month }}월</option>
            {% endfor %}
        </select>
        <button type="submit">Filter</button>
    </form>

    {% for record in records %}
        <div class="dairy_content">
            <a href="{% url 'records:diary' record.pk %}">
                <h4>{{ record.record_date|date:'m/d' }}</h4>
                <h4>{{ record.title }}</h4>
            </a>
        </div>
    {% empty %}
    <div class="dairy_content text-center fw-bold lh-1">
      <h4>♡기록이 없습니다♡<h4>
    </div>
    {% endfor %}
</div>

{% endblock content %}

정소담/records/templates/records/write.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'records/style.css' %}">
{% endblock style %}


{% block content %}

<h1>Today record</h1>

<form action="{% url 'records:success' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <label for="title">Title</label>
        <input type="text" class="form-control" name="title" id="title" required>
    </div>
    <div>
        <label for="record_date">Date</label>
        <input type="date" class="form-control" name="record_date" id="record_date" required>
    </div>
    <div>
        <label for="imgfile">Image</label>
        <input type="file" class="form-control" name="imgfile" id="imgfile">
    </div>
    <div>
        <label for="content">Content</label>
        <textarea name="content" class="form-control" id="content" cols="30" rows="5" required></textarea>
    </div>
    <div style="display: flex;justify-content: center;align-items: center;">
        <input class="btn" style="color:pink; font-size:30px;" type="submit" id='submit-button' value="Save">
        <a href="{% url 'records:record' %}" style="font-size:30px;">Back</a>
    </div>
</form>

{% endblock content %}