김신혜/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    # path('new/', views.new, name='new'),
    # path('create/', views.create, name='create'),
]

김신혜/do_it_django_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('', include('single_pages.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

김신혜/single_pages/urls.py
from django.urls import path
from . import views
app_name = 'single_pages'
urlpatterns = [
    path('about_me/', views.about_me, name='about_me'),
    path('', views.landing, name="landing"),
]

김신혜/blog/models.py
from django.db import models
# 파이썬 os모듈
import os

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True)
    content = models.TextField()
    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # author : 추후 작성 예정
    
    # __str__()함수 선언
    def __str__(self):
        # __str__()의 괄호 안에 들어오는 (매개변수)의 pk, title을 출력
        return f'[{self.pk}]{self.title}'
    
    # 각 레코드(filed모음)
    def get_absolute_url(self):
        return f'/blog/{self.pk}/'
    
    # 파일 경로는 제외하고 파일명만 나오게 하는 함수 생성
    def get_file_name(self):
        return os.path.basename(self.file_upload.name)
    
    # 확장자를 찾아내는 함수도 함께 생성
    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]
    

김신혜/single_pages/models.py
from django.db import models

# Create your models here.

김신혜/blog/views.py
# from django.shortcuts import render, redirect
from django.views.generic import ListView,  DetailView
from .models import Post

class PostList(ListView):
    model = Post
    ordering = '-pk'
    # template_name = 'blog/index.html'
    
class PostDetail(DetailView):
    model = Post

# Create your views here.
# def index(request):
#     posts = Post.objects.all().order_by('-pk')
#     return render(request, 'blog/index.html', {'posts':posts})

# def single_post_page(request, pk):
#     post = Post.objects.get(pk=pk)
#     return render(request, 'blog/single_post_page.html', {'post':post})

# def new(request):
#     return render(request, 'blog/new.html')

# def create(request):
#     title = request.POST.get('title')
#     content = request.POST.get('content')
#     post = Post(title=title, content=content)
#     post.save()
#     return redirect('blog:post_detail', post.pk)

김신혜/single_pages/views.py
from django.shortcuts import render

# Create your views here.
def landing(request):
    return render(request, 'single_pages/landing.html')

def about_me(request):
    return render(request, 'single_pages/about_me.html')

김신혜/blog/templates/blog/post_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>{{ post.title }} - Blog</title>
		<link
			rel="stylesheet"
			href="{% static 'blog/bootstrap/bootstrap.min.css' %}"
			media="screen" />
		<link
			rel="stylesheet"
			href="{% static 'blog/css/blog-post.css' %}"
			media="screen" />
		<script
			src="https://kit.fontawesome.com/9ab92bb101.js"
			crossorigin="anonymous"></script>
	</head>
	<body>
		<!-- Responsive navbar-->
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
			<div class="container-fluid container">
				<a class="navbar-brand" href="{% url 'single_pages:landing' %}">
					MyDjango
				</a>
				<button
					class="navbar-toggler"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#navbarNavDropdown"
					aria-controls="navbarNavDropdown"
					aria-expanded="false"
					aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNavDropdown">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item active">
							<a
								class="nav-link"
								aria-current="page"
								href="{% url 'single_pages:landing' %}">
								Home
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'blog:post_list' %}"> Blog </a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'single_pages:about_me' %}">
								About Me</a
							>
						</li>
						<li class="nav-item dropdown">
							<a
								class="nav-link dropdown-toggle"
								href="#"
								role="button"
								data-bs-toggle="dropdown"
								aria-expanded="false">
								Dropdown link
							</a>
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="#">Action</a></li>
								<li>
									<a class="dropdown-item" href="#">Another action</a>
								</li>
								<li>
									<a class="dropdown-item" href="#">Something else here</a>
								</li>
							</ul>
						</li>
					</ul>
					<ul class="navbar-nav ml-auto">
						<li class="nav-item">
							<a
								class="nav-link"
								href="#"
								data-bs-toggle="modal"
								data-bs-target="#Modal"
								>Log In</a
							>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		<!-- navbar Modal -->
		<div
			class="modal fade"
			id="Modal"
			tabindex="-1"
			aria-labelledby="logInModalLabel"
			aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title fs-5" id="logInModalLabel">Log In</h5>
						<button
							type="button"
							class="btn-close"
							data-bs-dismiss="modal"
							aria-label="Close"></button>
					</div>

					<!-- Model body -->
					<div class="modal-body">
						<div class="row">
							<div class="col-md-6">
								<button type="button" class="btn btn-outline-dark">
									Log in with Google
								</button>
								<button type="button" class="btn btn-outline-dark">
									Log in with E-mail
								</button>
							</div>
							<div class="col-md-6">
								<button type="button" class="btn btn-outline-dark">
									Sign Up with E-mail
								</button>
							</div>
						</div>
					</div>
					<div class="modal-footer">
						<button
							type="button"
							class="btn btn-secondary"
							data-bs-dismiss="modal">
							Close
						</button>
					</div>
				</div>
			</div>
		</div>

		<!-- Page content-->
		<div class="container mt-5">
			<div class="row">
				<div class="col-lg-8">
					<!-- Post content-->
					<article>
						<!-- Post header-->
						<header class="mb-4">
							<!-- Post title-->
							<h1 class="fw-bolder mb-1">{{ post.title }}</h1>
							<h5 class="text-muted">{{ post.hook_text }}</h5>
							<!-- Post meta content-->
							<div class="text-muted fst-italic mb-2">
								Posted on {{ post.created_at }} by <a href="#">작성자</a>
							</div>
							<!-- Post categories-->
							<a
								class="badge bg-secondary text-decoration-none link-light"
								href="#!"
								>Web Design</a
							>
							<a
								class="badge bg-secondary text-decoration-none link-light"
								href="#!"
								>Freebies</a
							>
						</header>
						<!-- Preview image figure-->
						<figure class="mb-4">
							{% if p.head_image %}
							<img
								class="img-fluid rounded"
								src="{{ post.head_image.url }}"
								alt="{{ post.title }} head_image" />
							{% else %}
							<img
								class="card-img-top"
								src="https://picsum.photos/seed/{{ p.id }}/800/200"
								alt="random_image" />
							{% endif %}
						</figure>
						<!-- Post content-->
						<section class="mb-5">
							<p class="fs-5 mb-4">{{ post.content }}</p>
							{% if post.file_upload %}
							<a
								href="{{ post.file_upload.url }}"
								class="btn btn-outline-dark"
								role="buttom"
								download
								>Download: {% if post.get_file_ext == 'csv' %}
								<i class="fa-solid fa-file-csv"></i>
								{% elif post.get_file_ext == 'xlsx' or post.get_file_ext ==
								'xls' %}
								<i class="fa-solid fa-file-excel"></i>
								{% elif post.get_file_ext == 'docx' or post.get_file_ext ==
								'doc' %}
								<i class="fa-solid fa-file-word"></i>
								{% else %}
								<i class="fa-solid fa-file"></i>
								{% endif %} {{ post.get_file_name }}
							</a>
							{% endif %}
							<hr />
							<p class="fs-5 mb-4">
								The universe is large and old, and the ingredients for life as
								we know it are everywhere, so there's no reason to think that
								Earth would be unique in that regard. Whether of not the life
								became intelligent is a different question, and we'll see if we
								find that.
							</p>
							<p class="fs-5 mb-4">
								If you get asteroids about a kilometer in size, those are large
								enough and carry enough energy into our system to disrupt
								transportation, communication, the food chains, and that can be
								a really bad day on Earth.
							</p>
							<h2 class="fw-bolder mb-4 mt-5">
								I have odd cosmic thoughts every day
							</h2>
							<p class="fs-5 mb-4">
								For me, the most fascinating interface is Twitter. I have odd
								cosmic thoughts every day and I realized I could hold them to
								myself or share them with people who might be interested.
							</p>
							<p class="fs-5 mb-4">
								Venus has a runaway greenhouse effect. I kind of want to know
								what happened there because we're twirling knobs here on Earth
								without knowing the consequences of it. Mars once had running
								water. It's bone dry today. Something bad happened there as
								well.
							</p>
						</section>
					</article>
					<!-- Comments section-->
					<section class="mb-5">
						<div class="card bg-light">
							<div class="card-body">
								<!-- Comment form-->
								<form class="mb-4">
									<textarea
										class="form-control"
										rows="3"
										placeholder="Join the discussion and leave a comment!"></textarea>
								</form>
								<!-- Comment with nested comments-->
								<div class="d-flex mb-4">
									<!-- Parent comment-->
									<div class="flex-shrink-0">
										<img
											class="rounded-circle"
											src="https://dummyimage.com/50x50/ced4da/6c757d.jpg"
											alt="..." />
									</div>
									<div class="ms-3">
										<div class="fw-bold">Commenter Name</div>
										If you're going to lead a space frontier, it has to be
										government; it'll never be private enterprise. Because the
										space frontier is dangerous, and it's expensive, and it has
										unquantified risks.
										<!-- Child comment 1-->
										<div class="d-flex mt-4">
											<div class="flex-shrink-0">
												<img
													class="rounded-circle"
													src="https://dummyimage.com/50x50/ced4da/6c757d.jpg"
													alt="..." />
											</div>
											<div class="ms-3">
												<div class="fw-bold">Commenter Name</div>
												And under those conditions, you cannot establish a
												capital-market evaluation of that enterprise. You can't
												get investors.
											</div>
										</div>
										<!-- Child comment 2-->
										<div class="d-flex mt-4">
											<div class="flex-shrink-0">
												<img
													class="rounded-circle"
													src="https://dummyimage.com/50x50/ced4da/6c757d.jpg"
													alt="..." />
											</div>
											<div class="ms-3">
												<div class="fw-bold">Commenter Name</div>
												When you put money directly to a problem, it makes a
												good headline.
											</div>
										</div>
									</div>
								</div>
								<!-- Single comment-->
								<div class="d-flex">
									<div class="flex-shrink-0">
										<img
											class="rounded-circle"
											src="https://dummyimage.com/50x50/ced4da/6c757d.jpg"
											alt="..." />
									</div>
									<div class="ms-3">
										<div class="fw-bold">Commenter Name</div>
										When I look at the universe and all the ways the universe
										wants to kill us, I find it hard to reconcile that with
										statements of beneficence.
									</div>
								</div>
							</div>
						</div>
					</section>
				</div>
				<!-- Side widgets-->
				<div class="col-lg-4">
					<!-- Search widget-->
					<div class="card mb-4">
						<div class="card-header">Search</div>
						<div class="card-body">
							<div class="input-group">
								<input
									class="form-control"
									type="text"
									placeholder="Enter search term..."
									aria-label="Enter search term..."
									aria-describedby="button-search" />
								<button
									class="btn btn-primary"
									id="button-search"
									type="button">
									Go!
								</button>
							</div>
						</div>
					</div>
					<!-- Categories widget-->
					<div class="card mb-4">
						<div class="card-header">Categories</div>
						<div class="card-body">
							<div class="row">
								<div class="col-sm-6">
									<ul class="list-unstyled mb-0">
										<li><a href="#!">Web Design</a></li>
										<li><a href="#!">HTML</a></li>
										<li><a href="#!">Freebies</a></li>
									</ul>
								</div>
								<div class="col-sm-6">
									<ul class="list-unstyled mb-0">
										<li><a href="#!">JavaScript</a></li>
										<li><a href="#!">CSS</a></li>
										<li><a href="#!">Tutorials</a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
					<!-- Side widget-->
					<div class="card mb-4">
						<div class="card-header">Side Widget</div>
						<div class="card-body">
							You can put anything you want inside of these side widgets. They
							are easy to use, and feature the Bootstrap 5 card component!
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Footer-->
		<footer class="py-5 bg-dark">
			<div class="container">
				<p class="m-0 text-center text-white">
					Copyright &copy; Your Website 2023
				</p>
			</div>
		</footer>

		<!-- bootstrap -->
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
			crossorigin="anonymous" />
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
			crossorigin="anonymous"></script>
	</body>
</html>

{% comment %} <img src="{{ post.head_image.url }}" alt="" /> {% endcomment %}

김신혜/blog/templates/blog/post_list.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>{{ post.title }} Blog</title>
		<link
			rel="stylesheet"
			href="{% static 'blog/bootstrap/bootstrap.min.css' %}"
			media="screen" />
	</head>
	<body>
		<!-- Responsive navbar-->
		<nav class="navbar navbar-expand-lg bg-body-tertiary">
			<div class="container-fluid container">
				<a class="navbar-brand" href="{% url 'single_pages:landing' %}">
					MyDjango
				</a>
				<button
					class="navbar-toggler"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#navbarNavDropdown"
					aria-controls="navbarNavDropdown"
					aria-expanded="false"
					aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNavDropdown">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item active">
							<a
								class="nav-link"
								aria-current="page"
								href="{% url 'single_pages:landing' %}">
								Home
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'blog:post_list' %}"> Blog </a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'single_pages:about_me' %}">
								About Me</a
							>
						</li>
						<li class="nav-item dropdown">
							<a
								class="nav-link dropdown-toggle"
								href="#"
								role="button"
								data-bs-toggle="dropdown"
								aria-expanded="false">
								Dropdown link
							</a>
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="#">Action</a></li>
								<li>
									<a class="dropdown-item" href="#">Another action</a>
								</li>
								<li>
									<a class="dropdown-item" href="#">Something else here</a>
								</li>
							</ul>
						</li>
					</ul>
					<ul class="navbar-nav ml-auto">
						<li class="nav-item">
							<a
								class="nav-link"
								href="#"
								data-bs-toggle="modal"
								data-bs-target="#Modal"
								>Log In</a
							>
						</li>
					</ul>
				</div>
			</div>

			<!-- Modal -->
			<div
				class="modal fade"
				id="Modal"
				tabindex="-1"
				aria-labelledby="logInModalLabel"
				aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<h5 class="modal-title fs-5" id="logInModalLabel">Log In</h5>
							<button
								type="button"
								class="btn-close"
								data-bs-dismiss="modal"
								aria-label="Close"></button>
						</div>

						<!-- Model body -->
						<div class="modal-body">
							<div class="row">
								<div class="col-md-6">
									<button type="button" class="btn btn-outline-dark">
										Log in with Google
									</button>
									<button type="button" class="btn btn-outline-dark">
										Log in with E-mail
									</button>
								</div>
								<div class="col-md-6">
									<button type="button" class="btn btn-outline-dark">
										Sign Up with E-mail
									</button>
								</div>
							</div>
						</div>
						<div class="modal-footer">
							<button
								type="button"
								class="btn btn-secondary"
								data-bs-dismiss="modal">
								Close
							</button>
						</div>
					</div>
				</div>
			</div>
		</nav>

		<!-- Page Content -->
		<div class="container my-3">
			<div class="row">
				<!-- Post Content -->
				<div class="col-md-8 col-lg-8" id="main-area">
					<h1>Blog</h1>
					<div class="mb-4">
						{% if post_list.exists %} {% for p in post_list %}
						<div class="card mb-4 bg-body-tertiary">
							<div class="card">
								{% if p.head_image %}
								<img
									class="card-img-top"
									src="{{ p.head_image.url }}"
									alt="{{ p }} head image" />
								{% else %}
								<img
									class="card-img-top"
									src="https://picsum.photos/seed/{{ p.id }}/800/200"
									alt="random_image" />
								{% endif %}
								<div class="card-body m-1">
									<h2 class="card-title">{{ p.title }}</h2>
									{% if p.hook_text %}
									<h5 class="text-muted">{{ p.hook_text }}</h5>
									{% endif %}
									<!-- 앞에서부터 45개 단어만 출력하도록 설정 -->
									<p class="card-text">{{ p.content | truncatewords:45 }}</p>
									<a class="btn btn-primary" href="{{ p.get_absolute_url }}"
										>Read more →</a
									>
								</div>
							</div>
							<div class="small text-muted m-3">
								Posted on {{ p.created_at }} by <a href="#">작성자명</a>
							</div>
						</div>

						{% endfor %} {% else %}
						<h3>아직 게시물이 없습니다.</h3>
						{% endif %}
					</div>

					<!-- Pagination-->
					<ul class="pagination justify-content-center mb-4">
						<li class="page-item">
							<a class="page-link" href="#">&larr; </a>
						</li>
						<li class="page-item disabled">
							<a class="page-link" href="#!">...</a>
						</li>
						<li class="page-item disabled">
							<a class="page-link" href="#!"> &rarr;</a>
						</li>
					</ul>
				</div>

				<!-- Side widget-->
				<div class="col-md-4">
					<!-- Search widget-->
					<div class="card mb-4">
						<h3 class="card-header">Search</h3>
						<div class="card-body">
							<div class="input-group">
								<input
									class="form-control"
									type="text"
									placeholder="Enter search term..."
									aria-label="Enter search term..."
									aria-describedby="button-search" />
								<button
									class="btn btn-primary"
									id="button-search"
									type="button">
									Go!
								</button>
							</div>
						</div>
					</div>

					<!-- Categories widget-->
					<div class="card mb-4">
						<h3 class="card-header">Categories</h3>
						<div class="card-body">
							<div class="row">
								<div class="col-sm-6">
									<ul class="list-unstyled mb-0">
										<li><a href="#!">Web Design</a></li>
										<li><a href="#!">HTML</a></li>
										<li><a href="#!">Freebies</a></li>
									</ul>
								</div>
								<div class="col-sm-6">
									<ul class="list-unstyled mb-0">
										<li><a href="#!">JavaScript</a></li>
										<li><a href="#!">CSS</a></li>
										<li><a href="#!">Tutorials</a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Footer-->
		<footer class="py-5 bg-dark">
			<div class="container">
				<p class="m-0 text-center text-white">
					&copy; shinhye Kim's Website 2023
				</p>
			</div>
		</footer>
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
			crossorigin="anonymous" />
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
			crossorigin="anonymous"></script>
	</body>
</html>

김신혜/single_pages/templates/single_pages/landing.html
<!DOCTYPE html>
<html lang="ko">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Homepage</title>
		<link
			href="./bootstrap/css/bootstrap-grid.min.css"
			rel="stylesheet"
			type="text/css" />
		<!-- 자바스크립트 코드는 script태그 안에 담는다. -->
		<script type="text/javascript" src="plus_function.js"></script>
		<script type="text/javascript" src="now_time.js"></script>
	</head>
	<body>
		<!-- Responsive navbar-->
		<nav class="navbar navbar-expand-lg bg-body-tertiary">
			<div class="container-fluid container">
				<a class="navbar-brand" href="{% url 'single_pages:landing' %}">
					MyDjango
				</a>
				<button
					class="navbar-toggler"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#navbarNavDropdown"
					aria-controls="navbarNavDropdown"
					aria-expanded="false"
					aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNavDropdown">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item active">
							<a
								class="nav-link"
								aria-current="page"
								href="{% url 'single_pages:landing' %}">
								Home
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'blog:post_list' %}"> Blog </a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'single_pages:about_me' %}">
								About Me</a
							>
						</li>
						<li class="nav-item dropdown">
							<a
								class="nav-link dropdown-toggle"
								href="#"
								role="button"
								data-bs-toggle="dropdown"
								aria-expanded="false">
								Dropdown link
							</a>
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="#">Action</a></li>
								<li>
									<a class="dropdown-item" href="#">Another action</a>
								</li>
								<li>
									<a class="dropdown-item" href="#">Something else here</a>
								</li>
							</ul>
						</li>
					</ul>
					<ul class="navbar-nav ml-auto">
						<li class="nav-item">
							<a
								class="nav-link"
								href="#"
								data-bs-toggle="modal"
								data-bs-target="#Modal"
								>Log In</a
							>
						</li>
					</ul>
				</div>
			</div>
		</nav>

		<!-- Modal -->
		<div
			class="modal fade"
			id="Modal"
			tabindex="-1"
			aria-labelledby="logInModalLabel"
			aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title fs-5" id="logInModalLabel">Log In</h5>
						<button
							type="button"
							class="btn-close"
							data-bs-dismiss="modal"
							aria-label="Close"></button>
					</div>

					<!-- Model body -->
					<div class="modal-body">
						<div class="row">
							<div class="col-md-6">
								<button type="button" class="btn btn-outline-dark">
									Log in with Google
								</button>
								<button type="button" class="btn btn-outline-dark">
									Log in with E-mail
								</button>
							</div>
							<div class="col-md-6">
								<button type="button" class="btn btn-outline-dark">
									Sign Up with E-mail
								</button>
							</div>
						</div>
					</div>
					<div class="modal-footer">
						<button
							type="button"
							class="btn btn-secondary"
							data-bs-dismiss="modal">
							Close
						</button>
					</div>
				</div>
			</div>
		</div>

		<h1>Home</h1>
		<h2>landing</h2>
		<h2>메인 홈페이지 입니다.</h2>
		<a href="#">[CREATE]</a>

		<button onclick="nowTime()">현재시간</button>
		<hr />

		<label for="inputA">a</label>
		<input id="inputA" value="1" onkeyup="덧셈함수()" />
		<label for="inputB">b</label>
		<input id="inputB" value="2" onkeyup="덧셈함수()" />

		<p>
			<span id="valueA">1</span> + <span id="valueB">2</span> =
			<span id="valueC">3</span>입니다.
		</p>
		<a href="https://www.google.co.kr" role="button" class="btn btn-primary"
			>Google</a
		>
		<img src="./photo03.jpeg" width="600px" />
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
			crossorigin="anonymous" />
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
			crossorigin="anonymous"></script>
	</body>
</html>