정소담/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),   
]

정소담/diaries/urls.py
from django.urls import path
from . import views

app_name = 'diaries'
urlpatterns = [
    path('', views.diary, name='diary'),
    path('<int:pk>/', views.diarypage, name='diarypage'),
    path('write/', views.write, name='write'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name = 'edit'),
    path('calendar/',views.calendar, name='calendar'),
]

정소담/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('records/', include('records.urls')),
    path('', views.main, name='main'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

정소담/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

정소담/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('main')
    else:
        form = AuthenticationForm()
        form.fields['username'].label = "아이디"
        form.fields['username'].widget.attrs['style'] = "border: 1px rgb(201, 186, 244) solid; border-radius: 10px;"
        form.fields['username'].widget.attrs['placeholder'] = "   ID"
        form.fields['password'].widget.attrs['style'] = "border: 1px rgb(201, 186, 244) solid; border-radius: 10px;"
        form.fields['password'].widget.attrs['placeholder'] = "   Password"
    
    context = {
        'form' : form,
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('main')

정소담/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock style %}

{% block content %}

<div class="box">
    <div class="title">
        <h1>로그인</h1>
    </div>
    <div class="login_input">
        <form action="{% url 'accounts:login' %}" method="POST" >
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn_style" value= "Login">
            <a href="{% url 'main' %}" class="btn btn_style">Back</a>
        </form>
    </div>
</div>

{% endblock content %}